# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: msbuild /p:Configuration=$(buildConfiguration) "NETCore Examples/BowlingKata-SpecFlowJson-xUnit/Bowling.sln"
  displayName: 'msbuild $(buildConfiguration)'

- script: dotnet test --no-build "NETCore Examples/BowlingKata-SpecFlowJson-xUnit/Bowling.SpecFlowXUnit/Bowling.SpecFlowXUnit.csproj" ---logger trx --configuration $(buildConfiguration)
  displayName: dotnet test $(buildConfiguration) 
