# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  solution: "NETCore Examples/BowlingKata-SpecFlowJson-xUnit/Bowling.sln" 

steps:

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: 4.x

- task: NuGetCommand@2
  inputs:
    restoreSolution: $(solution)
    
- task: MSBuild@1
  inputs:
    solution: $(solution)
    configuration: $(buildConfiguration)
  displayName: 'msbuild $(buildConfiguration)'

- script: dotnet test --no-build "NETCore Examples/BowlingKata-SpecFlowJson-xUnit/Bowling.SpecFlowXUnit/Bowling.SpecFlowXUnit.csproj" --logger trx --configuration $(buildConfiguration)
  displayName: dotnet test $(buildConfiguration) 

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '*.trx'
    mergeTestResults: true
